/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Usuario;
import Modelo.UsuarioDAO;
import Vista.RegistroUsuarios;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ni-va
 */
public class Usuarios extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Usuarios.class.getName());

    /**
     * Creates new form RegistrarUsuario
     */
    UsuarioDAO dao = new UsuarioDAO();

    public Usuarios() {
        initComponents();
        DefaultTableModel modeloEditable = new DefaultTableModel(
                new Object[][]{},
                new String[]{"id_usuario", "nombre_usuario", "apellido", "contrasena", "rol"}
        ) {

            boolean[] canEdit = new boolean[]{false, true, true, true, true};

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };

        jTable1_usuarios.setModel(modeloEditable);
        listar();
    }

    public void listar() {
        DefaultTableModel modelo = (DefaultTableModel) jTable1_usuarios.getModel();
        modelo.setRowCount(0);

        List<Usuario> lista = dao.listarUsuarios();
        for (Usuario u : lista) {
            modelo.addRow(new Object[]{
                u.getid_usuario(),
                u.getnombre_usuario(),
                u.getApellido(),
                u.getContrasena(),
                u.getRol()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1_eliminar_Usuario = new javax.swing.JButton();
        jButton2_exportar_excel = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_usuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1_eliminar_Usuario.setText("Eliminar");
        jButton1_eliminar_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_eliminar_UsuarioActionPerformed(evt);
            }
        });

        jButton2_exportar_excel.setText("Exportar Excel");
        jButton2_exportar_excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_exportar_excelActionPerformed(evt);
            }
        });

        jButton3.setText("Actualizar tabla");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id_usuario", "nombre_usuario", "apellido", "contrasena", "rol"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_usuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_usuarios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1_eliminar_Usuario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2_exportar_excel)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jButton1_eliminar_Usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2_exportar_excel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_eliminar_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_eliminar_UsuarioActionPerformed
        int fila = jTable1_usuarios.getSelectedRow();

        if (fila == 1) {
            JOptionPane.showMessageDialog(null, "Seleccione un usuario");
            return;
        }

        int id = Integer.parseInt(jTable1_usuarios.getValueAt(fila, 0).toString());

        if (dao.eliminar(id)) {
            JOptionPane.showMessageDialog(null, "Usuario eliminado");
            listar();
        } else {
            JOptionPane.showMessageDialog(null, "Error al eliminar");
        }
    }//GEN-LAST:event_jButton1_eliminar_UsuarioActionPerformed

    private void jTable1_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_usuariosMouseClicked

    }//GEN-LAST:event_jTable1_usuariosMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int fila = jTable1_usuarios.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione una fila para actualizar");
            return;
        }

        try {
            Usuario u = new Usuario();

            u.setid_usuario(Integer.parseInt(jTable1_usuarios.getValueAt(fila, 0).toString()));
            u.setnombre_usuario(jTable1_usuarios.getValueAt(fila, 1).toString());
            u.setApellido(jTable1_usuarios.getValueAt(fila, 2).toString());
            u.setContrasena(jTable1_usuarios.getValueAt(fila, 3).toString());
            u.setRol(jTable1_usuarios.getValueAt(fila, 4).toString());

            if (dao.actualizar(u)) {
                JOptionPane.showMessageDialog(null, "Usuario actualizado");
                listar();
            } else {
                JOptionPane.showMessageDialog(null, "Error al actualizar");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2_exportar_excelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_exportar_excelActionPerformed

        if (dao.exportarExcel(jTable1_usuarios)) {  // ← AQUI ENVÍAS LA TABLA, NO LA LISTA
            JOptionPane.showMessageDialog(null,
                    "Archivo Excel generado exitosamente como 'usuarios.xlsx'");
        } else {
            JOptionPane.showMessageDialog(null,
                    "Error al generar el archivo Excel");
        }

    }//GEN-LAST:event_jButton2_exportar_excelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Usuarios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_eliminar_Usuario;
    private javax.swing.JButton jButton2_exportar_excel;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_usuarios;
    // End of variables declaration//GEN-END:variables
}
